services:

  frontend:
    build:
      context: /home/$USER/acs-fe
      dockerfile: Dockerfile
    ports:
      - "80:80"  # Change port as necessary
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./target:/app/target
      - ./logs:/app/logs
    environment:
      DB_HOST: 192.168.90.101
      DB_PORT: 5432
      DB_NAME: acsDB
      DB_USERNAME: apollo
      DB_PASSWORD: root
    ports:
      - "7547:7547"
    networks:
      - app-network
    depends_on:
      - frontend
    command: ./mvnw spring-boot:run

networks:
  app-network:
    driver: bridge
