# Log file name and location
logging.file.name=/app/logs/application.log
logging.file.max-size=10MB
logging.level.root=DEBUG

### DATABASE
spring.profiles.active=@activatedProperties@
spring.datasource.url=jdbc:postgresql://10.160.0.51:5433/acsDB
spring.datasource.username=apollo
spring.datasource.password=ap0ll0ap0ll0!
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_schema=acsdb

server.port=7547


CoreThreads = 4
MaxCoreThreads = 10
  
